name: sealed-secrets
description: Helm chart for the sealed-secrets controller.

version: 1.16.1
appVersion: v0.16.0

icon: https://avatars0.githubusercontent.com/u/34656521?s=200&v=4
kubeVersion: ">=1.16.0-0"
home: https://github.com/bitnami-labs/sealed-secrets
apiVersion: v2
type: application
maintainers:
- name: mkmik
  email: mmikulicic@gmail.com
